apiVersion: v1
kind: Service
metadata:
  name: fluxai-cloudflare-service
spec:
  selector:
    deploymentInformation: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
  ports:
  - protocol: TCP
    port: 8080 # Port on the service
    targetPort: 8080 # Port on the pods
  type: NodePort
